[project]
name = "3530566279"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.4.6",
    "pillow>=12.3.0",
    "requests>=2.34.2",
    "torch>=2.14.0",
]

[tool.uv]
# PyPI 走清华源, PyTorch 走南大镜像 (CUDA 12.8 专用 wheel)
index-url = "https://pypi.tuna.tsinghua.edu.cn/simple"
find-links = ["https://mirrors.aliyun.com/pytorch-wheels/cu132/"]
